### ISSUE TITLE
new alot of errors

### ISSUE THREAD

**Issue by Djizox** [oscarpedrero/Notify#9]
![Skærmbillede 2024-05-25 021313](https://github.com/oscarpedrero/BloodyNotify/assets/11280026/0b8c93f9-caf6-457e-8839-c5eff20b7a87)
   at BloodyNotify.Systems.KillVBloodSystem.OnDetahVblood(VBloodSystem sender, NativeList`1 deathEvents)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Bloody.Core.API.v1.EventsHandlerSystem.OnDeathVBloodInvoke(VBloodSystem sender, NativeList`1 deathEvents)
[Error  :Bloody.Core] [02.13.21] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'NoPrefabName' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BloodyNotify.DB.Database.getPrefabNameValue(String prefabName)
   at BloodyNotify.Systems.KillVBloodSystem.GetAnnouncementMessage(String vblood)
   at BloodyNotify.Systems.KillVBloodSystem.SendAnnouncementMessage(String vblood)
   at BloodyNotify.Systems.KillVBloodSystem.OnDetahVblood(VBloodSystem sender, NativeList`1 deathEvents)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Bloody.Core.API.v1.EventsHandlerSystem.OnDeathVBloodInvoke(VBloodSystem sender, NativeList`1 deathEvents)
[Error  :Bloody.Core] [02.13.22] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'NoPrefabName' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BloodyNotify.DB.Database.getPrefabNameValue(String prefabName)
   at BloodyNotify.Systems.KillVBloodSystem.GetAnnouncementMessage(String vblood)
   at BloodyNotify.Systems.KillVBloodSystem.SendAnnouncementMessage(String vblood)
   at BloodyNotify.Systems.KillVBloodSystem.OnDetahVblood(VBloodSystem sender, NativeList`1 deathEvents)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Bloody.Core.API.v1.EventsHandlerSystem.OnDeathVBloodInvoke(VBloodSystem sender, NativeList`1 deathEvents)
[Error  :Bloody.Core] [02.13.22] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'NoPrefabName' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BloodyNotify.DB.Database.getPrefabNameValue(String prefabName)
   at BloodyNotify.Systems.KillVBloodSystem.GetAnnouncementMessage(String vblood)
   at BloodyNotify.Systems.KillVBloodSystem.SendAnnouncementMessage(String vblood)
   at BloodyNotify.Systems.KillVBloodSystem.OnDetahVblood(VBloodSystem sender, NativeList`1 deathEvents)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Bloody.Core.API.v1.EventsHandlerSystem.OnDeathVBloodInvoke(VBloodSystem sender, NativeList`1 deathEvents)

**Comment by oscarpedrero** [comment]
Send me complete log...  But it looks like you have modified the json files and they have some error...

**Comment by Djizox** [comment]
Only file I have edited is user_online.json by adding names that is shown on the other issue I opened.

**Comment by oscarpedrero** [comment]
@Djizox You are missing a comma at the end of each line of the `users_online.json` file, except for the last one which should not have it and that is why it is giving you an error...
